name: Auto Backport to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout develop with full history
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      # 2) Configure Git user
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Create the backport Pull Request
      - name: Create backport PR
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: backport changes from develop to main"
          title: "Auto Backport: develop → main"
          body: |
            This pull request was created automatically to backport changes from `develop` into `main`.
          base: main
          branch: backport/develop-into-main-${{ github.run_number }}
          delete-branch: true
          draft: false

      # 4) Debug: print the PR number
      - name: Debug PR number
        run: |
          PR_NUMBER="${{ steps.create_pr.outputs['pull-request-number'] }}"
          echo "Backport PR #${PR_NUMBER}"

      # 5) Attempt to enable GitHub’s Auto‑merge
      - name: Enable auto‑merge on backport PR
        id: auto_merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs['pull-request-number'] }}
          merge-method: merge

      # 6) Fallback: if auto‑merge was disallowed, merge via GH CLI using PAT
      - name: Fallback merge via GH CLI
        if: ${{ steps.auto_merge.outcome != 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR="${{ steps.create_pr.outputs['pull-request-number'] }}"
          echo "Auto‑merge failed, falling back to GH CLI merge for PR #${PR}"
          gh pr merge "$PR" \
            --repo "${{ github.repository }}" \
            --merge \
            --admin
