name: Auto Backport to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      # … steps 1–4: checkout, configure git, create PR, debug PR number …

      - name: Create backport PR
        id: backport_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: backport changes from develop to main"
          title: "Auto Backport: develop → main"
          body: |
            This PR backports changes from `develop` into `main`.
          base: main
          branch: backport/develop-into-main-${{ github.run_number }}
          delete-branch: true

      - name: Debug PR number
        run: |
          PR_NUMBER="${{ steps.backport_pr.outputs['pull-request-number'] }}"
          echo "Backport PR #${PR_NUMBER}"

      # Attempt auto‑merge (will fail if not enabled)
      - name: Enable auto‑merge on backport PR
        if: ${{ always() }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.backport_pr.outputs['pull-request-number'] }}
          merge-method: merge

      # Fallback: Merge with GH CLI using PAT
      - name: Fallback: merge PR via GH CLI
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER="${{ steps.backport_pr.outputs['pull-request-number'] }}"
          echo "Falling back to GH CLI merge for PR #${PR_NUMBER}"
          gh pr merge $PR_NUMBER \
            --repo ${{ github.repository }} \
            --merge \
            --admin
