name: Auto Backport to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout develop with full history
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      # 2) Create (or update) the backport PR
      - name: Create backport PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: backport changes from develop to main"
          title: "Backport develop → main"
          body: |
            This pull request was created automatically to backport changes from `develop` into `main`.
          base: main
          branch: backport/develop-into-main-${{ github.run_number }}
          delete-branch: true
          draft: false

      # 3) Debug: show the PR number in the logs
      - name: Debug PR number
        run: echo "Backport PR #${{ steps.cpr.outputs.pull-request-number }}"

      # 4) Auto-approve the PR to satisfy any review protection
      - name: Auto-approve backport PR
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      # 5) Enable GitHub’s Auto‑merge on the PR
      - name: Enable auto-merge on backport PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
