name: Auto Backport PR to Main

on:
  push:
    branches:
      - develop

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout de develop con todo el historial
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      # 2) Configurar Git para la acción de GH Actions
      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Crear el Pull Request de backport
      - name: Crear Pull Request de backport
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: backport cambios de develop a main"
          title: "Auto Backport: develop → main"
          body: |
            Este PR fue generado automáticamente para llevar los cambios de `develop` a `main`.
          base: main
          branch: backport/develop-into-main-${{ github.run_number }}
          draft: false
          delete-branch: true

      # 4) (Opcional) Habilitar auto‑merge una vez que pase los checks
      - name: Habilitar Auto‑Merge
        if: ${{ steps.create_pr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: merge