name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_PUBLIC_IP: ${{ vars.EC2_PUBLIC_IP }}
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      GIT_USER: innome
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configure SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts

      # 3. Deploy to EC2 (with Git user + token)
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$EC2_PUBLIC_IP << EOF
            # Set Git identity
            git config --global user.name "$GIT_USER"
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            
            cd /home/ubuntu/fang-template

            # Switch origin to HTTPS with token auth
            git remote set-url origin \
              "https://$GIT_USER:$GITHUB_TOKEN@github.com/NiValSas/fang-template.git"

            # Pull, rebuild, and restart
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
