name: Auto Backport to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Create backport PR
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}         # ← you must supply this
          commit-message: "chore: backport changes from develop to main"
          title: "Backport develop → main"
          body: |
            This pull request was created automatically to backport changes from `develop` into `main`.
          base: main
          branch: backport/develop-into-main-${{ github.run_number }}
          delete-branch: true
          draft: false

      - name: Debug PR number
        run: |
          PR="${{ steps.create_pr.outputs['pull-request-number'] }}"
          echo "Backport PR #${PR}"

      - name: Auto-approve backport PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}       # also needs token
          pull-request-number: ${{ steps.create_pr.outputs['pull-request-number'] }}

      - name: Enable auto-merge on backport PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}              # and here
          pull-request-number: ${{ steps.create_pr.outputs['pull-request-number'] }}
          merge-method: merge
