name: Sync develop into main

on:
  push:
    branches:
      - develop

jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout the full repo (develop by default)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # grab all history so we can merge

      # 2) Configure Git so pushes work
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Merge develop into main and push
      - name: Merge develop → main
        run: |
          # Use the GITHUB_TOKEN for push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main
          git checkout main
          git merge origin/develop --no-edit
          git push origin main
