      - name: Deploy to EC2 (zero-downtime with Docker Swarm)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$EC2_PUBLIC_IP << 'EOF'
            set -e

            cd /home/ubuntu/fang-template
            git pull origin main

            # 1) Asegurarnos de que Docker Swarm está inicializado
            if ! sudo docker info --format '{{.Swarm.LocalNodeState}}' | grep -q active; then
              sudo docker swarm init
            fi

            # 2) Construir y etiquetar la imagen
            sudo docker build -t fang-app:latest .

            # 3) Crear el servicio la primera vez
            if ! sudo docker service ls | grep -q fang_app; then
              sudo docker service create \
                --name fang_app \
                --replicas 2 \
                --publish 8000:8000 \
                fang-app:latest
            else
              # 4) Rolling update: un contenedor a la vez
              sudo docker service update \
                --image fang-app:latest \
                --update-parallelism 1 \
                --update-delay 10s \
                fang_app
            fi
          EOF
