name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se activará cuando se haga un push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # La clave privada SSH que has almacenado en los secrets de GitHub

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@<EC2_PUBLIC_IP> << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
