name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se activará cuando se haga un push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el código desde el repositorio de GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar SSH utilizando la clave privada desde los secrets de GitHub
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Carga la clave privada SSH desde los secrets de GitHub
          ssh-passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}  # Carga la passphrase desde los secrets de GitHub

      # 3. Desplegar a EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'  # Usamos el secreto para la IP pública
            cd /home/ubuntu/fang-template  # Cambiar al directorio donde se encuentra el proyecto
            git pull origin main  # Actualiza el código desde la rama 'main'
            docker-compose down  # Detiene los contenedores existentes
            docker-compose up -d  # Levanta los contenedores en segundo plano
          EOF
