name: Validate Branch Name

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name format
        run: |
          # For PR events, use the head ref; otherwise, strip 'refs/heads/'
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            branch_name="${{ github.head_ref }}"
          else
            branch_name="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch name is '$branch_name'"

          if [[ ! "$branch_name" =~ ^(feature|fix|hotfix)/.+ ]]; then
            echo "Error: Branch name must start with 'feature/', 'fix/', or 'hotfix/'."
            exit 1
          fi

          echo "✅ Branch name meets the required pattern."
