name: Validate Branch Name

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Validar formato de la rama
      run: |
        # obtenemos el nombre completo de la rama (p.ej. feature/fix-backport)
        branch_name=${GITHUB_REF#refs/heads/}
        echo "Branch name is '$branch_name'"
    
        if [[ ! "$branch_name" =~ ^(feature|fix|hotfix)/.+ ]]; then
          echo "Error: El nombre de la rama debe empezar con 'feature/', 'fix/' o 'hotfix/'."
          exit 1
        fi
    
        echo "✅ El nombre de la rama cumple el patrón."
